# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Walon的技术博客
subtitle: '欢迎，这里是Walon的博客'
description: ''
keywords:
author: Leon Walon
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://lowols.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
#theme: hexo-theme-matery
theme: butterfly

hexo_markmap:
  pjax: false
  katex: false
  highlight: false
  userCDN:
    d3_js: https://fastly.jsdelivr.net/npm/d3@6
    markmap_view_js: https://fastly.jsdelivr.net/npm/markmap-view@0.15.4
    webfont_js: https://fastly.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js
    katex_css: https://fastly.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
    hljs_css: https://fastly.jsdelivr.net/npm/@highlightjs/cdn-assets@11.8.0/styles/default.min.css
  lockView: false
  JSONOptions: "{}"

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:lowols/lowols.github.io.git
  branch: main

# algolia:
  # appId: "Z7A3XW4R2I"
  # apiKey: "12db1ad54372045549ef465881c17e743"
  # adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
  # chunkSize: 5000
  # indexName: "my-hexo-blog"
  # fields:
    # - content:strip:truncate,0,500
    # - excerpt:strip
    # - gallery
    # - permalink
    # - photos
    # - slug
    # - tags
    # - title
    
  
algolia:
  appId: "LT5E5X8OYT" #AppID
  apiKey: "fb3624e785e54a179df31308a732967b" #刚刚新建的API Key
  adminApiKey: "099094fb121e9065294044301ac5692d" #Admin API Key
  indexName: "hexo" #这个就是Indices填的
  chunkSize: 5000
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title